### ISSUE TITLE
GCViT model load fails for subclassed models

### ISSUE THREAD

**Issue by andreped** [awsaf49/gcvit-tf#20]
**Describe the bug**
I have been finetuning a `GCViTXXTiny` architecture on some image classification problem. As discussion in https://github.com/awsaf49/gcvit-tf/discussions/19, I managed to get it converging and all seems good.

However, when attempting to load the model, I ran into a `TypeError`. I have seemed something like this before when subclassing Keras Models, which I also do in this case.

In Keras', they have tried to go away from needing to set the `from_config()`/`get_config()` methods for custom layers/classes. However, I have seen multiple scenarios (at least with older tf versions <= 2.11) where this did not in fact work for all situations.

I think it might be necessary to add the aforementioned methods to all custom layers and classes, such that trained models can be loaded as normal. This was the default before and can also been seen is still done in Keras' own tutorials (see [here](https://keras.io/guides/functional_api/)).

Might be that we also need to add the `@keras.saving.register_keras_serializable()` decorator to all custom layers to make them properly serializable. Maybe that is the main problem here. Not sure.

**To Reproduce**
I have shared a simple [gist](https://colab.research.google.com/gist/andreped/bcd8fc0ae46f0b34587c3b02962a1a95/gcvit-model-load-bug.ipynb) to reproduce the error. For some reason, it does not reproduce it, but I believe there is something Im doing wrong in the simple reproducible script. Will update it if I find out what the problem is.

I simply finetuned a classifier architecture containing the GCViT as backbone, and tried to save and load it. It seems to fail at loading. It also complains during saving, which may be related to this issue.

**Error log**
```
Traceback (most recent call last):
  File "apps/train_lowres.py", line 242, in <module>
    main()
  File "apps/train_lowres.py", line 192, in main
    model = tf.keras.models.load_model(model_path + curr_time + "_" + curr_date + "_model_lowres_classifier_" + name, compile=False)
  File "/home/andrep/workspace/bcgrade/venv_latest/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/andrep/workspace/bcgrade/venv_latest/lib/python3.8/site-packages/keras/engine/training.py", line 3132, in from_config
    raise TypeError(
TypeError: Unable to revive model from config. When overriding the `get_config()`, make sure that the returned config contains all items used as arguments in the constructor to <class 'gcvit.models.gcvit.GCViT'>, which is the default behavior. You can override this default behavior by defining a `from_config` method to specify how to create an instance of GCViT from the config. 

Error encountered during deserialization:
__init__() missing 4 required positional arguments: 'window_size', 'dim', 'depths', and 'num_heads'
```

There was also these warnings when saving:
```
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.reshaping.zero_padding2d.ZeroPadding2D object at 0x7f16c0476040>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <gcvit.layers.feature.ReduceSize object at 0x7f16c028b3a0>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <keras.layers.reshaping.zero_padding2d.ZeroPadding2D object at 0x7f16c022a520>, because it is not built.
WARNING:absl:Found untraced functions such as proj_layer_call_fn, proj_layer_call_and_return_conditional_losses, _jit_compiled_convolution_op, conv_down_layer_call_fn, conv_down_layer_call_and_return_conditional_losses while saving (showing 5 of 1351). These functions will not be directly callable after loading.
WARNING:absl:<gcvit.layers.feature.Resizing object at 0x7f16c061e5e0> has the same name 'Resizing' as a built-in Keras object. Consider renaming <class 'gcvit.layers.feature.Resizing'> to avoid naming conflicts when loading with `tf.keras.models.load_model`. If renaming is not possible, pass the object in the `custom_objects` parameter of the load function.
WARNING:absl:<gcvit.layers.feature.Resizing object at 0x7f16c0529c40> has the same name 'Resizing' as a built-in Keras object. Consider renaming <class 'gcvit.layers.feature.Resizing'> to avoid naming conflicts when loading with `tf.keras.models.load_model`. If renaming is not possible, pass the object in the `custom_objects` parameter of the load function.
WARNING:absl:<gcvit.layers.feature.Resizing object at 0x7f16c0471100> has the same name 'Resizing' as a built-in Keras object. Consider renaming <class 'gcvit.layers.feature.Resizing'> to avoid naming conflicts when loading with `tf.keras.models.load_model`. If renaming is not possible, pass the object in the `custom_objects` parameter of the load function.
WARNING:absl:<gcvit.layers.feature.Resizing object at 0x7f16c02245e0> has the same name 'Resizing' as a built-in Keras object. Consider renaming <class 'gcvit.layers.feature.Resizing'> to avoid nami
```

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux, macOS, Windows] Ubuntu Linux
 - Version [e.g. 18.04] 20.04
 - TensorFlow: 2.11.0
 - Python: 3.8.10

**Comment by andreped** [comment]
The first model saving warning can likely be solved by simply renaming the custom `Resizing` layer seen [here](https://github.com/awsaf49/gcvit-tf/blob/main/gcvit/layers/feature.py#L264) to something else that does not collide with Keras' own built-in layer. Suggestion: `Resizer` or `TensorResizer`.

**Comment by andreped** [comment]
Perhaps I'm not building the backbone properly before training? Right now, I simply do:
```
import tensorflow as tf
from gcvit import GCViTXXTiny

base = GCViTXXTiny(input_shape=self.instance_size[1:], pretrain=True, resize_query=True)

# remove classifier head and pooling
base = tf.keras.models.Sequential(base.layers[:-2])
base.build((self.instance_size))
```

Before the base model is later added as part of a `tf.keras.Model` through the Functional API. Any ideas?

**Comment by andreped** [comment]
@awsaf49 Perhaps simply adding default arguments to this class is all that is required:
https://github.com/awsaf49/gcvit-tf/blob/371e736ab8a707025facdafbc9a75a4dd9016723/gcvit/models/gcvit.py#L83

Would make sense why it was complaining on those four variables at least, as those are the only variables in that class without default variables.

**Comment by andreped** [comment]
Might be that something broken in the commit: https://github.com/awsaf49/gcvit-tf/commit/720adf7e43e875daa880ab5588d16612f0f4dd6a

**Comment by andreped** [comment]
I tried to revert the changes in the aforementioned commit and tried to set default arguments to both the GCViT and GCViTLevel classes. See my fork [here](https://github.com/andreped/gcvit-tf/tree/model-load-fix). 

At least training starts, and after the first epoch, I attempt to save the model on disk and reload it from disk. This results in a new error:
```
Traceback (most recent call last):
  File "apps/train_lowres.py", line 242, in <module>
    main()
  File "apps/train_lowres.py", line 192, in main
    model = tf.keras.models.load_model(model_path + curr_time + "_" + curr_date + "_model_lowres_classifier_" + name, compile=False)
  File "/home/andrep/workspace/bcgrade/venv_latest/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/andrep/workspace/bcgrade/venv_latest/lib/python3.8/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 139, in restore
    raise ValueError(
ValueError: Received incompatible tensor with shape (3, 3, 3, 64) when attempting to restore variable with shape (3, 3, 3, 128) and name variables/0/.ATTRIBUTES/VARIABLE_VALUE.
```

Might be that setting defaults args to the four variables I mentioned results in something breaking. But I could not really see why that was so.

I would rather think this might be due to the `resize_query=True` we set to support different input size to the network is not really working properly when loading the model from disk afterwards. But this is only speculation.

**Comment by awsaf49** [comment]
@andreped Apologies, but I'm currently tied up with something important. I'll be available after September 24th to address this matter. Thanks for your patience regarding the delay.

**Comment by andreped** [comment]
Could the TF version that I am using that is not compatible. Im also using an older protobuf and Im subclassing the model. Lots of things it could be. I can try to debug it further tomorrow and see if I can make a reproducible gist.

Anyways, I dont expect you to look at it until you have time.

**Comment by awsaf49** [comment]
> Might be that something broke in the commit: [720adf7](https://github.com/awsaf49/gcvit-tf/commit/720adf7e43e875daa880ab5588d16612f0f4dd6a)

You are right this commit broke the code. I've reverted it.

**Comment by andreped** [comment]
Why is it necessary to use `tf.saved_model.LoadOptions` for both saving and loading of the model? I have not used that before.

**Comment by awsaf49** [comment]
It's actually not necessary to use `tf.saved_model.LoadOptions`, at least not in GPU/CPU. However, in TPU model runs on VM so it is required to load and save the model locally using `options`.
