### ISSUE TITLE
tensorflow 2.10

### ISSUE THREAD

**Issue by fakyras** [awsaf49/gcvit-tf#6]
I guess should work as-is by replacing 2.4.1 to 2.10 in requirements? kind of sad that pip wheel depends on the ancient tensorflow version

**Comment by awsaf49** [comment]
Actually, I kinda unwillingly set this up for Kaggle TPU as it comes with TF 2.4, It should work on TF 2.10 as I've tested on TF 2.6 (Kaggle GPU) and TF 2.9 (Colab). I guess got a bit biased towards kaggle 😅

**Comment by fakyras** [comment]
I completely understand. However, having this in production as a package is not an option now. Keep up the good work!

**Comment by awsaf49** [comment]
libraries like qubvel's `classification_models` & `efficientnet` omit tf in requirements, will that solve this issue?

**Comment by awsaf49** [comment]
I've updated the requirements :)
